[tool.poetry]
name = "heartpredapp"
version = "0.1.0"
description = ""
authors = ["Williamdreams89 <wdanquah@stu.ucc.edu.gh>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
